apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache-hpa
  maxReplicas: 5
  minReplicas: 1
  targetCPUUtilizationPercentage: 20
